apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-04
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-04-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-04:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        targetRevision: new-helm
        path: charts/kargo-demo
        helm:
          parameters:
          - name: image.name
            value: public.ecr.aws/nginx/nginx:placeholder
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-04-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.helm.parameters
