---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-05
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo-05
  namespace: kargo-demo-05
spec:
  promotionPolicies:
  - stageSelector:
      name: test
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true
  - stageSelector:
      name: prod
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-05
spec:
  subscriptions:
  - chart:
      repoURL: https://charts.bitnami.com/bitnami
      name: nginx
      semverConstraint: ^14.1.0
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      constraint: ^1.24.0
      strictSemvers: true
      discoveryLimit: 3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promo-process
  namespace: kargo-demo-05
spec:
  vars:
  - name: chartRepo
    value: https://charts.bitnami.com/bitnami
  - name: chartName
    value: nginx
  - name: imageRepo
    value: public.ecr.aws/nginx/nginx
  steps:
  - uses: set-metadata
    config:
      updates:
      - kind: Stage
        name: ${{ ctx.stage }}
        values:
          lastPromotedAt: ${{ now() }}
  - uses: set-metadata
    config:
      updates:
      - kind: Freight
        name: ${{ ctx.targetFreight.name }}
        values:
          lastPromoted:
            at: ${{ stageMetadata(ctx.stage).lastPromotedAt }}
            to: ${{ ctx.stage }}
  - uses: argocd-update
    config:
      apps:
      - name: ${{ ctx.project }}-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.chartRepo }}
          chart: ${{ vars.chartName }}
          desiredRevision: ${{ chartFrom(vars.chartRepo, vars.chartName).Version }}
          updateTargetRevision: true
          helm:
            images:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-05
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-05
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-05
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-05
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
