apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
stage: test
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      charts:
      - registryURL: https://charts.bitnami.com/bitnami
        name: nginx # Watch for new versions of this chart
        semverConstraint: ^14.1.0
      images:
      - repoURL: nginx # Watch for new versions of this image
        semverConstraint: ^1.24.0
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new chart version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat
  namespace: kargo-demo
stage: uat
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new charts and images
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-uat
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new chart version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new charts and images
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new chart version
