apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-01
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-01
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      # Watch this branch instead of main. This is the "trunk" for this example.
      branch: kustomize
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-01
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-01-test
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        updateTargetRevision: true # Update Application to reference the new commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-01
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-01-uat
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        updateTargetRevision: true # Update Application to reference the new commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-01
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-01-prod
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        updateTargetRevision: true  # Update Application to reference the new commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-01
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
