apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-19-test
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
  template:
    metadata:
      name: kargo-demo-19-{{stage}}
      labels:
        kargo.akuity.io/project: kargo-demo-19
        kargo.akuity.io/stage: "{{stage}}"
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-19:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        targetRevision: 19/stage/{{stage}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-19-{{stage}}
      syncPolicy: {}
