---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-13
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo-13
  namespace: kargo-demo-13
spec:
  promotionPolicies:
  - stageSelector:
      name: test
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kargo-demo-13
data:
  imageRepoURL: public.ecr.aws/nginx/nginx
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: manifests
  namespace: kargo-demo-13
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
  username: <github-username>
  password: <github-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-13
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      branch: kustomize
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: base-promo-process
  namespace: kargo-demo-13
spec:
  vars:
  - name: gitRepo
  - name: targetBranch
  - name: outPath
  - name: imageRepo
    value: public.ecr.aws/nginx/nginx
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - commit: ${{ commitFrom(vars.gitRepo).ID }}
        path: ./src
      - branch: ${{ vars.targetBranch }}
        create: true
        path: ${{ vars.outPath }}
  - uses: git-clear
    config:
      path: ${{ vars.outPath }}
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/base
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/stages/${{ ctx.stage }}
      outPath: ${{ vars.outPath }}
  - uses: git-commit
    as: commit
    config:
      path: ${{ vars.outPath }}
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: compose-output
    config:
      commit: ${{ task.outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-13
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: ${{ secret('manifests').repoURL }}
      - name: targetBranch
        value: 13/stage/${{ ctx.stage }}
      - name: outPath
        value: ./out
      steps:
      - task:
          name: base-promo-process
        as: base
      - uses: git-push
        config:
          path: ${{ vars.outPath }}
          targetBranch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.base.commit }}
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-13
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: ${{ secret('manifests').repoURL }}
      - name: targetBranch
        value: 13/stage/${{ ctx.stage }}
      - name: outPath
        value: ./out
      steps:
      - task:
          name: base-promo-process
        as: base
      - uses: git-push
        config:
          path: ${{ vars.outPath }}
          targetBranch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.base.commit }}
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-13
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: ${{ secret('manifests').repoURL }}
      - name: targetBranch
        value: 13/stage/${{ ctx.stage }}
      - name: outPath
        value: ./out
      steps:
      - task:
          name: base-promo-process
      - uses: git-push
        as: push
        config:
          path: ${{ vars.outPath }}
          generateTargetBranch: true
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: ${{ vars.gitRepo }}
          createTargetBranch: true
          sourceBranch: ${{ outputs.push.branch }}
          targetBranch: ${{ vars.targetBranch }}
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          repoURL: ${{ vars.gitRepo }}
          prNumber: ${{ outputs['open-pr'].prNumber }}
      - uses: argocd-update
        config:
          apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs['wait-for-pr'].commit }}
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-13
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
