apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-02
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-02-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-02:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: placeholder
        helm:
          parameters:
          - name: service.type
            value: ClusterIP
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-02-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.targetRevision
