apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - chart:
      registryURL: https://charts.bitnami.com/bitnami
      name: nginx # Watch for new versions of this chart
      semverConstraint: ^14.1.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
stage: test
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat
  namespace: kargo-demo
stage: uat
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new versions of the chart
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-uat
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new versions of the chart
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
