---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-09
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo-09
  namespace: kargo-demo-09
spec:
  promotionPolicies:
  - stageSelector:
      name: test
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: manifests
  namespace: kargo-demo-09
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
  username: <github-username>
  password: <github-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promo-process
  namespace: kargo-demo-09
spec:
  vars:
  - name: gitRepo
    value: ${{ secret('manifests').repoURL }}
  - name: targetBranch
    value: 09/stage/${{ ctx.stage }}
  - name: outPath
    value: ./out
  - name: usePR
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - commit: ${{ commitFrom(vars.gitRepo).ID }}
        path: ./src
      - branch: ${{ vars.targetBranch }}
        create: true
        path: ${{ vars.outPath }}
  - uses: git-clear
    config:
      path: ${{ vars.outPath }}
  - uses: copy
    config:
      inPath: ./src/base
      outPath: ${{ vars.outPath }}/base
  - uses: copy
    config:
      inPath: ./src/stages/${{ ctx.stage }}
      outPath: ${{ vars.outPath }}/stages/${{ ctx.stage }}
  - uses: git-commit
    as: commit
    config:
      path: ${{ vars.outPath }}
      message: updated manifests copied from main
  - uses: git-push
    as: push
    config:
      path: ${{ vars.outPath }}
      generateTargetBranch: ${{ vars.usePR }}
  - uses: git-open-pr
    as: open-pr
    if: ${{ vars.usePR }}
    config:
      repoURL: ${{ vars.gitRepo }}
      createTargetBranch: true
      sourceBranch: ${{ task.outputs.push.branch }}
      targetBranch: ${{ vars.targetBranch }}
  - uses: git-wait-for-pr
    as: wait-for-pr
    if: ${{ vars.usePR }}
    config:
      repoURL: ${{ vars.gitRepo }}
      prNumber: ${{ task.outputs['open-pr'].pr.id }}
  - uses: argocd-update
    config:
      apps:
      - name: ${{ ctx.project }}-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitRepo }}
          desiredRevision: "${{ vars.usePR ? task.outputs['wait-for-pr'].commit : task.outputs.push.commit }}"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-09
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      branch: kustomize
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-09
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: usePR
        value: ${{ false }}
      steps:
      - task:
          name: promo-process  
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-09
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      vars:
      - name: usePR
        value: ${{ false }}
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-09
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: usePR
        value: ${{ true }}
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-09
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
