apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-09
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: manifests
  namespace: kargo-demo-09
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
  username: <github-username>
  password: <github-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-09
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      # Watch this branch instead of main. This is the "trunk" for this example.
      branch: kustomize
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-09
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/<github-username>/kargo-demo-gitops.git
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      - name: targetBranch
        value: 09/stage/${{ ctx.stage }}
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - commit: ${{ commitFrom(vars.gitRepo).ID }}
            path: ${{ vars.srcPath }}
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ${{ vars.outPath }}
      - uses: git-clear
        config:
          path: ${{ vars.outPath }}
      - uses: copy
        config:
          inPath: ${{ vars.srcPath }}/base
          outPath: ${{ vars.outPath }}/base
      - uses: copy
        config:
          inPath: ${{ vars.srcPath }}/stages/${{ ctx.stage }}
          outPath: ${{ vars.outPath }}/stages/${{ ctx.stage }}
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.outPath }}
          message: updated manifests copied from main
      - uses: git-push
        config:
          path: ${{ vars.outPath }}
          targetBranch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-09
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/<github-username>/kargo-demo-gitops.git
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      - name: targetBranch
        value: 09/stage/${{ ctx.stage }}
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - commit: ${{ commitFrom(vars.gitRepo).ID }}
            path: ${{ vars.srcPath }}
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ${{ vars.outPath }}
      - uses: git-clear
        config:
          path: ${{ vars.outPath }}
      - uses: copy
        config:
          inPath: ${{ vars.srcPath }}/base
          outPath: ${{ vars.outPath }}/base
      - uses: copy
        config:
          inPath: ${{ vars.srcPath }}/stages/${{ ctx.stage }}
          outPath: ${{ vars.outPath }}/stages/${{ ctx.stage }}
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.outPath }}
          message: updated manifests copied from main
      - uses: git-push
        config:
          path: ${{ vars.outPath }}
          targetBranch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-09
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/<github-username>/kargo-demo-gitops.git
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      - name: targetBranch
        value: 09/stage/${{ ctx.stage }}
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - commit: ${{ commitFrom(vars.gitRepo).ID }}
            path: ${{ vars.srcPath }}
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ${{ vars.outPath }}
      - uses: git-clear
        config:
          path: ${{ vars.outPath }}
      - uses: copy
        config:
          inPath: ${{ vars.srcPath }}/base
          outPath: ${{ vars.outPath }}/base
      - uses: copy
        config:
          inPath: ${{ vars.srcPath }}/stages/${{ ctx.stage }}
          outPath: ${{ vars.outPath }}/stages/${{ ctx.stage }}
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.outPath }}
          message: updated manifests copied from main
      - uses: git-push
        as: push
        config:
          path: ${{ vars.outPath }}
          generateTargetBranch: true
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: ${{ vars.gitRepo }}
          createTargetBranch: true
          sourceBranch: ${{ outputs.push.branch }}
          targetBranch: ${{ vars.targetBranch }}
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          repoURL: ${{ vars.gitRepo }}
          prNumber: ${{ outputs['open-pr'].prNumber }}
      - uses: argocd-update
        config:
          apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs['wait-for-pr'].commit }}
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-09
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
