apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-18-test
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
  template:
    metadata:
      name: kargo-demo-18-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-18:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        targetRevision: 18/stage/{{stage}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-18-{{stage}}
      syncPolicy: {}
