apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-11
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-11-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-11:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        # Kargo will update this branch to move new commits from the helm branch
        # and/or new images into this stage
        targetRevision: 11/stage/{{stage}}
        path: charts/kargo-demo
        helm:
          valueFiles:
          - stages/{{stage}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-11-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
