---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-11
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo-11
  namespace: kargo-demo-11
spec:
  promotionPolicies:
  - stageSelector:
      name: regexp:^(test|uat)$
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: manifests
  namespace: kargo-demo-11
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
  username: <github-username>
  password: <github-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-11
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      branch: new-helm
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.24.0
      strictSemvers: true
      discoveryLimit: 3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promo-process
  namespace: kargo-demo-11
spec:
  vars:
  - name: gitRepo
    value: ${{ secret('manifests').repoURL }}
  - name: imageRepo
    value: public.ecr.aws/nginx/nginx
  - name: targetBranch
    value: 11/stage/${{ ctx.stage }}
  - name: outPath
    value: ./out
  - name: usePR
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - commit: ${{ commitFrom(vars.gitRepo).ID }}
        path: ./src
      - branch: ${{ vars.targetBranch }}
        create: true
        path: ${{ vars.outPath }}
  - uses: git-clear
    config:
      path: ${{ vars.outPath }}
  - uses: yaml-update
    as: update-image
    config:
      path: ./src/charts/kargo-demo/values.yaml
      updates:
      - key: image.name
        value: ${{ vars.imageRepo }}:${{ imageFrom(vars.imageRepo).Tag }}
  - uses: helm-template
    config:
      path: ./src/charts/kargo-demo
      releaseName: kargo-demo
      valuesFiles:
      - ./src/charts/kargo-demo/stages/${{ ctx.stage }}/values.yaml
      outPath: ${{ vars.outPath }}
  - uses: git-commit
    as: commit
    config:
      path: ${{ vars.outPath }}
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    as: push
    config:
      path: ${{ vars.outPath }}
      generateTargetBranch: ${{ vars.usePR == 'true' }}
  - uses: git-open-pr
    as: open-pr
    if: ${{ vars.usePR == 'true' }}
    config:
      repoURL: ${{ vars.gitRepo }}
      createTargetBranch: true
      sourceBranch: ${{ task.outputs.push.branch }}
      targetBranch: ${{ vars.targetBranch }}
  - uses: git-wait-for-pr
    as: wait-for-pr
    if: ${{ vars.usePR == 'true' }}
    config:
      repoURL: ${{ vars.gitRepo }}
      prNumber: ${{ task.outputs['open-pr'].pr.id }}
  - uses: argocd-update
    config:
      apps:
      - name: ${{ ctx.project }}-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitRepo }}
          desiredRevision: "${{ vars.usePR == 'true' ? task.outputs['wait-for-pr'].commit : task.outputs.push.commit }}"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-11
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: usePR
        value: "false"
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-11
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      vars:
      - name: usePR
        value: "false"
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-11
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: usePR
        value: "true"
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-11
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
