apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-08
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-08-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-08:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        targetRevision: placeholder
        path: stages/{{stage}}
        kustomize:
          images:
          - public.ecr.aws/nginx/nginx=public.ecr.aws/nginx/nginx:placeholder
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-08-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.targetRevision
    - .spec.source.kustomize.images
