apiVersion: v1
kind: Secret
metadata:
  name: artifactory-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret-token: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: generic-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: github-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret-token: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  auth-header: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-receiver
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterConfig
metadata:
  name: cluster
spec:
  gitClient:
    name: Kargo Test Key
    email: no-reply@kargo.io
    signingKeySecret:
      name: gpg-signing-key
  webhookReceivers:
  - name: artifactory
    artifactory:
      secretRef:
        name: artifactory-receiver
  - name: azure
    azure:
      secretRef:
        name: azure-receiver
  - name: bitbucket
    bitbucket:
      secretRef:
        name: bitbucket-receiver
  - name: dockerhub
    dockerhub:
      secretRef:
        name: dockerhub-receiver
  - name: generic
    generic:
      secretRef:
        name: generic-receiver
      actions:
      - action: Refresh
        whenExpression: "request.header('X-Event-Type') == 'push'"
        targetSelectionCriteria:
        - kind: Warehouse
          name: kargo-demo
  - name: github
    github:
      secretRef:
        name: github-receiver
  - name: gitlab
    gitlab:
      secretRef:
        name: gitlab-receiver
  - name: harbor
    harbor:
      secretRef:
        name: harbor-receiver
  - name: quay
    quay:
      secretRef:
        name: quay-receiver
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github
  namespace: kargo-shared-resources
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: "^https://github.com/<github-username>/.*"
  repoURLIsRegex: "true"
  username: <github-username>
  password: <github-pat>
# ---
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: github
#   namespace: kargo-shared-resources
#   labels:
#     kargo.akuity.io/cred-type: git
# stringData:
#   repoURL: "^https://github.com/<github-username>/.*"
#   repoURLIsRegex: "true"
#   githubAppClientID: <github-app-client-id>
#   githubAppPrivateKey: |
#     -----BEGIN RSA PRIVATE KEY-----
#     <placeholder-for-github-app-private-key>
#     -----END RSA PRIVATE KEY-----
#   githubAppInstallationID: <github-app-installation-id>
---
apiVersion: v1
kind: Secret
metadata:
  name: gpg-signing-key
  namespace: kargo-system-resources
  labels:
    kargo.akuity.io/cred-type: generic
type: Opaque
stringData:
  signingKey: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----
    <placeholder>
    -----END PGP PRIVATE KEY BLOCK-----
