apiVersion: v1
kind: Secret
metadata:
  name: artifactory-receiver
  namespace: kargo-cluster-secrets
data:
  secret-token: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-receiver
  namespace: kargo-cluster-secrets
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-receiver
  namespace: kargo-cluster-secrets
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-receiver
  namespace: kargo-cluster-secrets
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: github-receiver
  namespace: kargo-cluster-secrets
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-receiver
  namespace: kargo-cluster-secrets
data:
  secret-token: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-receiver
  namespace: kargo-cluster-secrets
data:
  auth-header: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-receiver
  namespace: kargo-cluster-secrets
data:
  secret: c295bGVudCBncmVlbiBpcyBwZW9wbGU=
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterConfig
metadata:
  name: cluster
spec:
  webhookReceivers:
  - name: artifactory
    artifactory:
      secretRef:
        name: artifactory-receiver
  - name: azure
    azure:
      secretRef:
        name: azure-receiver
  - name: bitbucket
    bitbucket:
      secretRef:
        name: bitbucket-receiver
  - name: dockerhub
    dockerhub:
      secretRef:
        name: dockerhub-receiver
  - name: github
    github:
      secretRef:
        name: github-receiver
  - name: gitlab
    gitlab:
      secretRef:
        name: gitlab-receiver
  - name: harbor
    harbor:
      secretRef:
        name: harbor-receiver
  - name: quay
    quay:
      secretRef:
        name: quay-receiver
